//created on: Apr 19, 2021
package rules;
import com.sample.Map;
import com.sample.Player;
import com.sample.GameHandler;
import com.sample.Action;
import com.sample.Turn;

//list any import classes here.



//declare any global variables here



rule "Game exists"
	when
		$g: GameHandler()
	then
		System.out.println("Game started");
		$g.spawnPlayers();
		System.out.println($g.getMap());
		$g.initGame();
		Player currPlayer = $g.getCurrentPlayer();
		Turn turn = new Turn(currPlayer, $g.getMap().getPlayerPOIs(currPlayer));
		insert(turn);
end

rule "Turn: interaction"
	when
		GameHandler($m: map)
		Turn($p: player, POIs.length > 0)
	then
		System.out.println("Interaction "+$p);
end

rule "Turn: movement"
	when
		GameHandler($m: map)
		Turn($p: player, POIs.length == 0)
	then
		System.out.println("Movement "+$p);
end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
